# NB. We don't include_guard this file set; every time it's included, all tests
# should be allowed to run.

include(pm__core)
include(pm_boolean)  # system under test
include(pm_fail)     # required to fail the tests out

# TODO: This is the poorest man's test suite. We should do... everything better.
#       First steps are probably to wrap the test in a macro that deals with
#       pass/fail checking, and not throw FATAL_ERROR on exit

function(pm_run_boolean_tests)
    message(STATUS "Running Postmodern Boolean Test suite")

    pm_bool(NOT V TRUE)
    pm_fail(UNLESS NOT V)
    pm_bool(NOT V FALSE)
    pm_fail(UNLESS     V)

    set(V FALSE)
    pm_bool(NOT V V)
    pm_fail(UNLESS V)

    set(V FALSE)
    pm_bool(NOT V)
    pm_fail(UNLESS V)


    pm_bool(AND V TRUE TRUE)
    pm_fail(UNLESS V)

    pm_bool(AND V TRUE FALSE)
    pm_fail(UNLESS NOT V)
    pm_bool(AND V FALSE TRUE)
    pm_fail(UNLESS NOT V)
    pm_bool(AND V FALSE FALSE)
    pm_fail(UNLESS NOT V)

    pm_bool(AND V TRUE TRUE TRUE TRUE)
    pm_fail(UNLESS     V)
    pm_bool(AND V FALSE TRUE TRUE TRUE)
    pm_fail(UNLESS NOT V)
    pm_bool(AND V TRUE TRUE TRUE FALSE)
    pm_fail(UNLESS NOT V)


    pm_bool(OR V TRUE TRUE)
    pm_fail(UNLESS V)

    pm_bool(OR V TRUE FALSE)
    pm_fail(UNLESS     V)
    pm_bool(OR V FALSE TRUE)
    pm_fail(UNLESS     V)
    pm_bool(OR V FALSE FALSE)
    pm_fail(UNLESS NOT V)

    pm_bool(OR V TRUE TRUE TRUE TRUE)
    pm_fail(UNLESS     V)
    pm_bool(OR V FALSE TRUE TRUE TRUE)
    pm_fail(UNLESS     V)
    pm_bool(OR V TRUE TRUE TRUE FALSE)
    pm_fail(UNLESS     V)
    pm_bool(OR V TRUE FALSE FALSE FALSE)
    pm_fail(UNLESS     V)
    pm_bool(OR V FALSE FALSE FALSE FALSE)
    pm_fail(UNLESS NOT V)


    pm_bool(XOR V TRUE TRUE)
    pm_fail(UNLESS NOT V)
    pm_bool(XOR V FALSE TRUE)
    pm_fail(UNLESS     V)
    pm_bool(XOR V TRUE FALSE)
    pm_fail(UNLESS     V)
    pm_bool(XOR V FALSE FALSE)
    pm_fail(UNLESS NOT V)

    pm_bool(XOR V TRUE TRUE TRUE TRUE)
    pm_fail(UNLESS NOT V)

    pm_bool(XOR V FALSE TRUE TRUE TRUE)
    pm_fail(UNLESS     V)
    pm_bool(XOR V TRUE FALSE TRUE TRUE)
    pm_fail(UNLESS     V)
    pm_bool(XOR V TRUE TRUE FALSE TRUE)
    pm_fail(UNLESS     V)
    pm_bool(XOR V TRUE TRUE TRUE FALSE)
    pm_fail(UNLESS     V)

    pm_bool(XOR V TRUE TRUE FALSE FALSE)
    pm_fail(UNLESS NOT V)
    pm_bool(XOR V TRUE FALSE TRUE FALSE)
    pm_fail(UNLESS NOT V)
    pm_bool(XOR V TRUE FALSE FALSE TRUE)
    pm_fail(UNLESS NOT V)
    pm_bool(XOR V FALSE TRUE TRUE FALSE)
    pm_fail(UNLESS NOT V)
    pm_bool(XOR V FALSE TRUE FALSE TRUE)
    pm_fail(UNLESS NOT V)
    pm_bool(XOR V FALSE FALSE TRUE TRUE)
    pm_fail(UNLESS NOT V)

    pm_bool(XOR V TRUE FALSE FALSE FALSE)
    pm_fail(UNLESS     V)
    pm_bool(XOR V FALSE TRUE FALSE FALSE)
    pm_fail(UNLESS     V)
    pm_bool(XOR V FALSE FALSE TRUE FALSE)
    pm_fail(UNLESS     V)
    pm_bool(XOR V FALSE FALSE FALSE TRUE)
    pm_fail(UNLESS     V)


    pm_bool(ANY V TRUE)
    pm_fail(UNLESS     V)
    pm_bool(ANY V FALSE)
    pm_fail(UNLESS NOT V)
    pm_bool(ANY V TRUE TRUE)
    pm_fail(UNLESS     V)
    pm_bool(ANY V TRUE FALSE)
    pm_fail(UNLESS     V)
    pm_bool(ANY V FALSE TRUE)
    pm_fail(UNLESS     V)
    pm_bool(ANY V FALSE FALSE)
    pm_fail(UNLESS NOT V)
    pm_bool(ANY V TRUE TRUE TRUE)
    pm_fail(UNLESS     V)
    pm_bool(ANY V FALSE TRUE TRUE)
    pm_fail(UNLESS     V)
    pm_bool(ANY V TRUE TRUE FALSE)
    pm_fail(UNLESS     V)
    pm_bool(ANY V FALSE TRUE FALSE)
    pm_fail(UNLESS     V)
    pm_bool(ANY V FALSE FALSE FALSE)
    pm_fail(UNLESS NOT V)
    unset(NOT_A_VAR)
    pm_bool(ANY V ${NOT_A_VAR})
    pm_fail(UNLESS NOT V)

    pm_bool(ALL V TRUE)
    pm_fail(UNLESS     V)
    pm_bool(ALL V FALSE)
    pm_fail(UNLESS NOT V)
    pm_bool(ALL V TRUE TRUE)
    pm_fail(UNLESS     V)
    pm_bool(ALL V TRUE FALSE)
    pm_fail(UNLESS NOT V)
    pm_bool(ALL V FALSE TRUE)
    pm_fail(UNLESS NOT V)
    pm_bool(ALL V FALSE FALSE)
    pm_fail(UNLESS NOT V)
    pm_bool(ALL V TRUE TRUE TRUE)
    pm_fail(UNLESS     V)
    pm_bool(ALL V FALSE TRUE TRUE)
    pm_fail(UNLESS NOT V)
    pm_bool(ALL V TRUE TRUE FALSE)
    pm_fail(UNLESS NOT V)
    pm_bool(ALL V FALSE TRUE FALSE)
    pm_fail(UNLESS NOT V)
    pm_bool(ALL V FALSE FALSE FALSE)
    pm_fail(UNLESS NOT V)
    pm_bool(ALL V ${NOT_A_VAR})
    pm_fail(UNLESS NOT V)

    pm_bool(ONE V TRUE)
    pm_fail(UNLESS     V)
    pm_bool(ONE V FALSE)
    pm_fail(UNLESS NOT V)
    pm_bool(ONE V TRUE TRUE)
    pm_fail(UNLESS NOT V)
    pm_bool(ONE V TRUE FALSE)
    pm_fail(UNLESS     V)
    pm_bool(ONE V FALSE TRUE)
    pm_fail(UNLESS     V)
    pm_bool(ONE V FALSE FALSE)
    pm_fail(UNLESS NOT V)
    pm_bool(ONE V TRUE TRUE TRUE)
    pm_fail(UNLESS NOT V)
    pm_bool(ONE V FALSE TRUE TRUE)
    pm_fail(UNLESS NOT V)
    pm_bool(ONE V TRUE TRUE FALSE)
    pm_fail(UNLESS NOT V)
    pm_bool(ONE V FALSE TRUE FALSE)
    pm_fail(UNLESS     V)
    pm_bool(ONE V FALSE FALSE FALSE)
    pm_fail(UNLESS NOT V)
    pm_bool(ONE V ${NOT_A_VAR})
    pm_fail(UNLESS NOT V)

    pm_bool(NONE V TRUE)
    pm_fail(UNLESS NOT V)
    pm_bool(NONE V FALSE)
    pm_fail(UNLESS     V)
    pm_bool(NONE V TRUE TRUE)
    pm_fail(UNLESS NOT V)
    pm_bool(NONE V TRUE FALSE)
    pm_fail(UNLESS NOT V)
    pm_bool(NONE V FALSE TRUE)
    pm_fail(UNLESS NOT V)
    pm_bool(NONE V FALSE FALSE)
    pm_fail(UNLESS     V)
    pm_bool(NONE V TRUE TRUE TRUE)
    pm_fail(UNLESS NOT V)
    pm_bool(NONE V FALSE TRUE TRUE)
    pm_fail(UNLESS NOT V)
    pm_bool(NONE V TRUE TRUE FALSE)
    pm_fail(UNLESS NOT V)
    pm_bool(NONE V FALSE TRUE FALSE)
    pm_fail(UNLESS NOT V)
    pm_bool(NONE V FALSE FALSE FALSE)
    pm_fail(UNLESS     V)
    pm_bool(NONE V ${NOT_A_VAR})
    pm_fail(UNLESS     V)

    message(STATUS "Running Postmodern Boolean Test suite -- done")
endfunction()
